version: 2
updates:
  - package-ecosystem: "npm"
    directory: "src/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "src/frontend"
    schedule:
      interval: "weekly"
